GET http://192.168.0.22/recuperar

###

POST http://192.168.0.22/validarCredenciais
Content-Type: application/x-www-form-urlencoded

username=admin&password=admin

###

POST http://192.168.0.22/salvar
Content-Type: application/json

{
  "ssid": "CLARO_D4D094",
  "senha": "NYJmv24gGv",
  "ipServidor": "192.168.1.1",
  "portaServidor": "8080",
  "token": "default_token",
  "inicioZona1": "10",
  "fimZona1": "20",
  "inicioZona2": "20",
  "fimZona2": "30",
  "inicioZona3": "30",
  "fimZona3": "40"
}

 